### ISSUE TITLE
Try to get mb-math working with TruffleRuby

### ISSUE THREAD

**Issue by mike-bourgeous** [mike-bourgeous/mb-math#8]
Based on a conversation elsewhere, it would be nice to see if TruffleRuby can run my math and sound code faster than CRuby.  This would help with the synthesizer demo from mb-surround and my future videos.

- [ ] https://github.com/oracle/truffleruby/issues/1589 for the GNUplot wrapper
- [ ] Make sure RSpec tests pass in TruffleRuby
- [x] Add TruffleRuby to CI matrix

**Comment by mike-bourgeous** [comment]
I've worked around the absence of `PTY` by rescuing `LoadError` in plot.rb.  See commit e08d9573b09fd96863055f01db70394c83eedc56.

**Comment by mike-bourgeous** [comment]
So far I've run into two TruffleRuby crashes/uncaught exceptions:

- One while running `rspec`
  - Infinite or NaN (java.lang.NumberFormatException) within my `PrecisionMethods#ceil`
- One while running `pry` (on mb-util)
  - Index: 46548, Size: 46548 (java.lang.IndexOutOfBoundsException) within TruffleRuby's readline implementation

**Comment by mike-bourgeous** [comment]
![image](https://user-images.githubusercontent.com/5015814/141400134-8185b7de-3c21-4abf-a513-dab9f23a70c7.png)

![image](https://user-images.githubusercontent.com/5015814/141400227-a15f877f-1d98-4ab9-80c9-793cc657c67a.png)

**Comment by mike-bourgeous** [comment]
When rspec does run, in addition to the expected plotting failures, there are parsing failures for complex numbers, and differences in default rounding mode.

**Comment by mike-bourgeous** [comment]
Saw a repeatable segfault in rspec with seed 17464:

![image](https://user-images.githubusercontent.com/5015814/141401074-d8fffbb9-f4ea-448b-878e-e9c2f66e8d7f.png)

[truffleruby-mb-math-segfault.txt](https://github.com/mike-bourgeous/mb-math/files/7524565/truffleruby-mb-math-segfault.txt)

**Comment by mike-bourgeous** [comment]
Failures from https://github.com/mike-bourgeous/mb-math/runs/4185434515?check_suite_focus=true --

- 1\) MB::M.parse_complex raises an error for "invalid"
     Failure/Error: expect { MB::M.parse_complex(k) }.to raise_error(v)
       expected ArgumentError but nothing was raised
- 2\) MB::M.parse_complex parses "1 + 1i" correctly
     Failure/Error: expect(MB::M.round(MB::M.parse_complex(k), 10)).to eq(MB::M.round(v, 10))

       expected: (1+1i)
            got: (1+0i)
- 10\) MB::M::PrecisionMethods#round with positive figs rounds NArrays
      Failure/Error: expect(MB::M.round(Numo::SFloat[-0.00125, 1.23456], 4)).to eq([-0.0013, 1.2346])

        expected: [-0.0013, 1.2346]
             got: Numo::SFloat#shape=[2]
        [-0.0012, 1.2346]
- truffleruby: an internal exception escaped out of the interpreter,
please report it to https://github.com/oracle/truffleruby/issues.

  ```
  Infinite or NaN (java.lang.NumberFormatException)
	from java.math.BigDecimal.<init>(BigDecimal.java:923)
	from java.math.BigDecimal.<init>(BigDecimal.java:900)
	from org.truffleruby.core.numeric.BigIntegerOps.fromDouble(BigIntegerOps.java:263)
	from org.truffleruby.core.numeric.FixnumOrBignumNode.fixnumOrBignum(FixnumOrBignumNode.java:65)
	from org.truffleruby.core.numeric.FloatNodes$FloatCeilPrimitiveNode.ceil(FloatNodes.java:554)
	from org.truffleruby.core.numeric.FloatNodesFactory$FloatCeilPrimitiveNodeFactory$FloatCeilPrimitiveNodeGen.execute(FloatNodesFactory.java:2946)
	from org.truffleruby.language.control.IfElseNode.execute(IfElseNode.java:43)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:36)
	from org.truffleruby.language.RubyMethodRootNode.execute(RubyMethodRootNode.java:58)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:650)
      /home/runner/work/mb-math/mb-math/lib/mb/m/precision_methods.rb:42:in `ceil'
	from /home/runner/work/mb-math/mb-math/lib/mb/m/precision_methods.rb:42:in `sigfigs'
	from /home/runner/work/mb-math/mb-math/spec/lib/mb/m/special_functions_spec.rb:86:in `block (4 levels) in <top (required)>'
  ```

**Comment by gogainda** [comment]
@mike-bourgeous I would recommend to open up corresponding issues in truffleruby repository

**Comment by mike-bourgeous** [comment]
Probably not going to work with TruffleRuby for now.  May revisit in the future.
